name: Mock Security Workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 0 * * 0'  # Run weekly on Sundays at midnight

permissions:
  security-events: write
  actions: read
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Mock Install dependencies
      run: |
        echo "Running npm install..."

    - name: Mock Build project
      run: |
        echo "Running npm run build..."

  unit_test:
    name: Unit Test
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Mock Install dependencies
      run: |
        echo "Running npm install..."

    - name: Mock Run unit tests
      run: |
        echo "Running npm run test..."

  deploy_staging:
    name: Deploy Staging
    runs-on: ubuntu-latest
    needs: unit_test

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Mock Deploy to staging
      run: |
        echo "Deploying to staging environment..."

  pentest:
    name: Pentest
    runs-on: ubuntu-latest
    needs: deploy_staging

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Run mock pentest
      run: |
        echo "Running API pentest..."
        echo "Checking input validation..."
        echo "Checking authorization..."
        echo "Vulnerability found: Improper authorization handling detected in API endpoint '/api/auth'"

    - name: Generate mock SARIF file with Markdown
      run: |
        cat << 'EOF' > results.sarif
        {
          "$schema": "https://raw.githubusercontent.com/oasis-tcs/sarif-spec/master/Schemata/sarif-schema-2.1.0.json",
          "version": "2.1.0",
          "runs": [
            {
              "tool": {
                "driver": {
                  "name": "Mock Security Scanner",
                  "informationUri": "https://example.com/mock-scanner",
                  "rules": [
                    {
                      "id": "AUTH001",
                      "shortDescription": {
                        "text": "Improper Authorization Handling"
                      },
                      "fullDescription": {
                        "text": "This rule checks for improper handling of authorization in the API."
                      },
                      "help": {
                        "text": "Authorization issues can lead to unauthorized access to sensitive information.",
                        "markdown": "# Detailed Security Report\n\n## Vulnerability: Improper Authorization Handling\n\n### Overview\nThis vulnerability occurs when an API endpoint fails to properly verify a user's authorization level, potentially allowing unauthorized access to sensitive data.\n\n### Affected File\n- **File:** `src/api/auth.js`\n- **Line Number:** 120\n\n### Severity\n- **Security Severity:** High (9.0/10)\n\n### Impact\nUnauthorized users could gain access to restricted API endpoints, compromising the security of sensitive information.\n\n### Steps to Reproduce\n1. Send a request to `/api/auth` without valid authorization tokens.\n2. Observe the response containing sensitive information.\n\n### Suggested Fix\n- Implement proper authorization checks using middleware.\n- Ensure all API endpoints validate user roles and permissions.\n\n### References\n- [OWASP Authorization Cheat Sheet](https://cheatsheetseries.owasp.org/cheatsheets/Authorization_Cheat_Sheet.html)\n\n### Evidence\n![Authorization Flaw Screenshot](https://example.com/screenshot.png)\n\n### Summary Table\n| Property             | Value                |\n|----------------------|----------------------|\n| **Vulnerability ID** | AUTH001              |\n| **Severity**         | High                 |\n| **Precision**        | High                 |\n| **Tags**             | Security, Authorization |\n\n---\nFor more details on fixing this issue, consult the [full documentation](https://example.com/mock-scanner/AUTH001)."
                      },
                      "defaultConfiguration": {
                        "level": "error"
                      },
                      "properties": {
                        "tags": ["security", "authorization"],
                        "precision": "high",
                        "security-severity": "9.0"
                      }
                    }
                  ]
                }
              },
              "results": [
                {
                  "ruleId": "AUTH001",
                  "level": "error",
                  "message": {
                    "text": "Improper authorization handling detected in API endpoint '/api/auth'"
                  },
                  "locations": [
                    {
                      "physicalLocation": {
                        "artifactLocation": {
                          "uri": "src/api/auth.js"
                        },
                        "region": {
                          "startLine": 120
                        }
                      }
                    }
                  ]
                }
              ]
            }
          ]
        }
        EOF

    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: results.sarif
