name: Pentest Security Workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 0 * * 0' # Run weekly on Sundays at midnight

permissions:
  security-events: write
  actions: read
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          echo "Running npm install..."

      - name: Build project
        run: |
          echo "Running npm run build..."

  unit_test:
    name: Unit Test
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          echo "Running npm install..."

      - name: Run unit tests
        run: |
          echo "Running npm run test..."

  deploy_staging:
    name: Deploy Staging
    runs-on: ubuntu-latest
    needs: unit_test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to staging
        run: |
          echo "Deploying to staging environment..."

  pentest:
    name: Pentest
    runs-on: ubuntu-latest
    needs: deploy_staging

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Script setup
        run: chmod +x ./scripts/run_pentest.sh ./scripts/generate_sarif.sh

      - name: Run Pentest
        id: run_pentest
        run: ./scripts/pentest.sh

      - name: Generate SARIF file
        run: ./scripts/report.sh

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif

      - name: Vulnerability found
        if: steps.run_pentest.outputs.VULNERABILITY_FOUND == 'true'
        run: |
          echo -e "\033[0;31m\033[1mVulnerability detected. Failing the workflow.\033[0m"
          exit 1
